name: Auto-Update RSS Feed

on:
  schedule:
    - cron: '0 * * * *' # ہر گھنٹے میں ایک بار چلے گا
  workflow_dispatch: # Manual run کے لیے

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Run RSS Generator
        run: php index.php

      - name: Push changes
  run: |
    git config --global user.name 'GitHub Action'
    git config --global user.email 'actions@github.com'
    git add .
    git commit -m "Auto-update RSS feed [skip ci]" || echo "No changes to commit"
    git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/rafaqatalirose/netfilix.git
