name: Auto RSS Update

on:
  push:
    branches:
      - main

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'actions@github.com'

      - name: Push changes
        run: |
          git add .
          git commit -m "Auto-update RSS feed [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/rafaqatalirose/netfilix.git
          
      
