name: Auto Update RSS Feed

on:
  schedule:
    - cron: '0 * * * *' # Har ghante chalega

  workflow_dispatch: # Manual run ka option

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Fetch RSS Feed
      run: |
        curl -o feed.xml "https://your-rss-feed-url.com/rss"

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add feed.xml
        git commit -m "Update RSS feed" || echo "No changes to commit"
        git push
